package mainApplication;

import java.io.File;
import java.io.FileFilter;
import java.io.FileInputStream;

import com.mysql.cj.protocol.Resultset;
import javafx.application.Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;
import java.sql.*;

public class __init__ extends Application {

	@FXML
	private AnchorPane rootAnchorPane;
	@FXML
	private Label userNameLabel;
	@FXML
	private Label passwordLabel;
	@FXML
	private TextField userField;
	@FXML
	private PasswordField passwordField;
	@FXML
	private Button loginButton;
	@FXML
	private Button createAccountButton;
	static Statement executer;

	public static void main(String[] args) {
		launch(args);
	}

	static Statement connectToDatabase(){
		try{
			String host = "jdbc:mysql://localhost:3306/test";
			String user = "hardik";
			String Password = "hardik";
			Connection con = DriverManager.getConnection(host,user,Password);
			Statement executer = con.createStatement();
			return executer;
		}
		catch(Throwable t){
			System.out.println("Please setup database");
			System.exit(0);
		}
		return null;
	}

	@FXML
	public void onLoginClicked(MouseEvent event) throws SQLException {
		String username = userField.getText();
		String password = passwordField.getText();
		boolean isValidUser = authenticate(username,password);
		if(isValidUser){
			System.out.println("Yes, user found");
		}
		else{
			System.out.println("User not found");
		}
	}

	private boolean authenticate(String username,String password) throws SQLException {
		String query = "Select * from userAccounts where username='"+username+"' and password='"+password+"';";
		ResultSet rs = executer.executeQuery(query);
		if(!rs.next()){
			return false;
		}
		return true;
	}

	// Event Listener on Button[#createAccountButton].onMouseClicked
	@FXML
	public void onSignUp(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("unimplemented");
	}

	@Override
	public void start(Stage mainStage) throws Exception {
		String pathtoFXML = "src/resources/fxml/__init__window__.fxml";
		FXMLLoader loader = new FXMLLoader();
		System.out.println("Apple");
		FileInputStream fxmlStream = new FileInputStream(pathtoFXML);
		AnchorPane root = (AnchorPane) loader.load(fxmlStream);
		Scene sc = new Scene(root);
		sc.getStylesheets().add("file:src/resources/css/mainWindow.css");
		mainStage.setScene(sc);
		mainStage.setResizable(false);
		mainStage.show();

		executer = __init__.connectToDatabase();

	}



}
