package resources.fxml;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.PasswordField;

import javafx.scene.input.MouseEvent;

public class __init__window__Controller {
	@FXML
	private AnchorPane rootAnchorPane;
	@FXML
	private Label userNameLabel;
	@FXML
	private Label passwordLabel;
	@FXML
	private TextField userField;
	@FXML
	private PasswordField passwordField;
	@FXML
	private Button loginButton;
	@FXML
	private Button createAccountButton;

	// Event Listener on Button[#loginButton].onMouseClicked
	@FXML
	public void onLoginClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#createAccountButton].onMouseClicked
	@FXML
	public void onSignUp(MouseEvent event) {
		// TODO Autogenerated
	}
}
